apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cinatunnel
  description: Client for CinaTunnels
  annotations:
    cinatunnel.com/software-excellence-opt-in: "true"
    cinatunnel.com/jira-project-key: "TUN"
    cinatunnel.com/jira-project-component: "CinaTunnel"
  tags:
    - internal
spec:
  type: "service"
  lifecycle: "Active"
  owner: "teams/tunnel-teams-routing"
  cf:
    compliance:
      fedramp-high: "pending"
      fedramp-moderate: "yes"
    FIPS: "required"
