# use a builder image for building cinatunnel
FROM golang:1.24 AS builder
ENV GO111MODULE=on \
  CGO_ENABLED=0 \
  CONTAINER_BUILD=1

WORKDIR /go/src/github.com/cinagroup/cinatunnel/

COPY . .

RUN GOOS=linux GOARCH=amd64 make cinatunnel

FROM gcr.io/distroless/base-debian13:nonroot

LABEL org.opencontainers.image.source="https://github.com/cinagroup/cinatunnel"

COPY --from=builder --chown=nonroot /go/src/github.com/cinagroup/cinatunnel/cinatunnel /usr/local/bin/

USER 65532:65532

ENTRYPOINT ["cinatunnel", "--no-autoupdate"]
CMD ["version"]
